### ISSUE TITLE
Memory leak with Flutter Session Replay

### ISSUE THREAD

**Issue by ioannisj** [PostHog/posthog-flutter#142]
### Description

from: https://posthog.com/questions/memory-leak-with-flutter-session-replay

**Comment by marandaneto** [comment]
Asked questions on the link.

**Comment by JobiJoba** [comment]
I have the same error message but when I have a TextFormField on the page and SessionReplay activated. 

Once the focus in on the TextFormField I get that error message every seconds

flutter: Error: Failed to capture screenshot.
flutter: Snapshot is the same as the last one.

My page also has SVG but removing them didn't change anything to the message - I don't know if it leads to a memory leak. 


```dart 
class OnboardingPage extends StatelessWidget {
  const OnboardingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Form(
          child: Column(
            children: [
              TextFormField(
                 decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Enter your character name',
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a name';
                  }
                  return null;
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

A simple example of how I use it in my project.

**Comment by marandaneto** [comment]
> flutter: Snapshot is the same as the last one.

this is not an error btw, it's just logging.

**Comment by marandaneto** [comment]
> I have the same error message but when I have a TextFormField on the page and SessionReplay activated.
> 
> Once the focus in on the TextFormField I get that error message every seconds
> 
> flutter: Error: Failed to capture screenshot. flutter: Snapshot is the same as the last one.
> 
> My page also has SVG but removing them didn't change anything to the message - I don't know if it leads to a memory leak.
> 
> ```dart
> class OnboardingPage extends StatelessWidget {
>   const OnboardingPage({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: SafeArea(
>         child: Form(
>           child: Column(
>             children: [
>               TextFormField(
>                  decoration: const InputDecoration(
>                   border: OutlineInputBorder(),
>                   labelText: 'Enter your character name',
>                 ),
>                 validator: (value) {
>                   if (value == null || value.isEmpty) {
>                     return 'Please enter a name';
>                   }
>                   return null;
>                 },
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> my config
> 
> ```dart
> final config =
>         PostHogConfig('xxx')
>           ..debug = kDebugMode
>           ..captureApplicationLifecycleEvents = true
>           ..host = 'https://us.i.posthog.com'
>           ..sessionReplay = true
>           ..sessionReplayConfig.maskAllTexts = false
>           ..sessionReplayConfig.maskAllImages = false;
> ```
> 
> A simple example of how I use it in my project using 4.9.1.

@JobiJoba this looks like a different issue, mind creating a new issue and providing an MRE? a sample where I can just run and reproduce the issue since I can't reproduce it myself? Thanks.
I'll need to know which OS, version, Flutter version, etc.

**Comment by waskalien** [comment]
Hello everyone,
I’d like to apologize for the delay in providing this MRE regarding this memory leak. After further investigation, I’ve created a simple example that reliably reproduces the issue:

**Main**
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:provider/provider.dart';
import 'package:vize/core/config/analytics.dart';
import 'package:vize/core/config/env.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Env.load();
  await AnalyticsConfig.configurePostHog();

  runApp(
    ChangeNotifierProvider<AppViewModel>(
      create: (_) => AppViewModel(),
      child: const App(),
    ),
  );
}

class AppViewModel with ChangeNotifier {
  AppViewModel() {
    Timer.periodic(const Duration(milliseconds: 100), (_) {
      notifyListeners();
    });
  }
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: <Widget>[
      SvgPicture.asset('assets/icons/profile/0.svg'),
      Consumer<AppViewModel>(builder: (BuildContext context, AppViewModel viewModel, _) {
        return SizedBox.shrink();
      })
    ]);
  }
}
```

**PostHog Configuration**
```dart
import 'package:posthog_flutter/posthog_flutter.dart';
import 'package:vize/core/config/env.dart';

class AnalyticsConfig {
  AnalyticsConfig._();

  static Future<void> configurePostHog() async {
    final PostHogConfig config = PostHogConfig(Env.posthogApiKey)
      ..debug = false
      ..captureApplicationLifecycleEvents = false
      ..host = 'https://us.i.posthog.com'
      ..sessionReplay = true
      ..sessionReplayConfig.maskAllTexts = false
      ..sessionReplayConfig.maskAllImages = false
      ..sessionReplayConfig.throttleDelay = const Duration(milliseconds: 500);

    await Posthog().setup(config);
  }
}
```

- When sessionReplayConfig.throttleDelay is lowered, the memory leak accelerates.
- Increasing the Timer.periodic duration (e.g., 10 second instead of 100ms) eliminates the leak.
- Disabling SessionReplay eliminates the leak.
- The memory leak worsens as more SVGs are added to the page.

Tested on iOS 18.1

**flutter version:** 3.27.3
**posthog_flutter version:**: 4.10.2 and olders
**provider version:**: 6.1.2

Let me know if further details or adjustments to the MRE are needed, and thanks for your help in investigating this!

**Comment by marandaneto** [comment]
@waskalien, which tools are you using to check for memory increase? standard [memory view](https://docs.flutter.dev/tools/devtools/memory)?
Can you provide an MRE repo where I can just run the project? It should include your full MRE with size, provider, flutter_svg, etc. Since my sample with a simple SVG isn't enough, thanks.

**Comment by marandaneto** [comment]
@waskalien https://github.com/waskalien/posthog-session-replay-memory-leak/blob/68b7b0a7d3abb39634cd3c3d378a066a01491f54/lib/main.dart#L39-L41
is this something realistic? Session replay will only take a screenshot (or consume memory) if there are screen changes; apparently, you are forcing that.
If you remove that, do you still see an issue?
Is there a memory leak, or is it just consuming more memory? They are different things, though.

**Comment by marandaneto** [comment]
<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/0a67dae2-8c11-47ca-a104-0ebf4bb8be11" />

So using the [memory view](https://docs.flutter.dev/tools/devtools/memory) on Dart/Flutter, the memory is pretty stable.

**Comment by marandaneto** [comment]
Improvements such as https://github.com/PostHog/posthog-flutter/issues/165 could help here, improving performance overall and not only the leak, I mean.

**Comment by marandaneto** [comment]
I found something here https://github.com/PostHog/posthog-flutter/pull/166 but it didnt improve much so its not the cause

**Comment by marandaneto** [comment]
So I finally narrowed down the issue to [this line](https://github.com/PostHog/posthog-flutter/blob/91d8ea9dceeca8e572015c601a2a6fc0411d291e/lib/src/replay/screenshot/screenshot_capturer.dart#L97).

The problem isn't really memory leaking but a similar side effect.

We need an image so we have to call `renderObject.toImage(...)`, and when we don't need it anymore, we call `image.dispose()` correctly, pretty much rather away.

The problem is that your screen is updating way too often, so we have to generate way too many images and the Dart/Flutter GC isn't running as often as it should, so a lot of images are in memory, because calling `dispose` is just a signal to be released, but only the Dart GC has the ability to free everything.

There's no way to call the GC manually sadly.

I think the best approach here is for you to increase your `throttleDelay` as much as possible or disable recordings for some specific screens that have constant animations. This would be possible with this [feat request](https://github.com/PostHog/posthog-flutter/issues/124), but it's not done yet.

**Comment by marandaneto** [comment]
@waskalien thanks for that.
I understand your point but I just don't have control over the GC, I cannot release the image after using it, we call `dispose` right away and that's the only thing we can do.
Do you have any other ideas?

**Comment by RCVZ** [comment]
@marandaneto I think it's because the image is passed to `_getImageBytes`, a new handle is created. All handles need to be disposed of before GC can it up.  Have you tried `debugGetOpenHandleStackTraces`?



<img width="1000" alt="Image" src="https://github.com/user-attachments/assets/d977022a-19eb-4054-baef-a90e1ee5dbc2" />

**Comment by marandaneto** [comment]
nope, `debugGetOpenHandleStackTraces` is new to me, will check today

**Comment by marandaneto** [comment]
The only thing I see is:

> #0      new Image._.<anonymous closure> (dart:ui/painting.dart:1932:32)
> #1      new Image._ (dart:ui/painting.dart:1934:6)
> #2      _NativeScene.toImage.<anonymous closure>.<anonymous closure> (dart:ui/compositing.dart:72:26)

and once I call `.dispose`, `debugGetOpenHandleStackTraces` always returns empty

**Comment by RCVZ** [comment]
Okay, then I was probably wrong. I thought that since the image was passed to `_getImageBytes`, a new handle would be created within `_getImageBytes`.

**Comment by marandaneto** [comment]
quite a few improvements here https://github.com/PostHog/posthog-flutter/releases/tag/5.23.2
curious if that helps, closing this issue since a lot has changed since then
let us know if you still have issues. An MRE would be super useful
