### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-flutter#51]
https://posthog.com/questions/flutter-for-windows-support

The Flutter SDK depends on the Android and iOS SDK.
Ideally, the SDK would also have a pure Dart client that works on Desktop.

**Comment by marandaneto** [comment]
A workaround, for now, would be to create a Flutter bridge and call a Native SDK via FFI, eg, [Rust SDK](https://github.com/PostHog/posthog-rs)

**Comment by CaptainDario** [comment]
Is there anything planned in regard to this?
I would like to switch to this plugin but I need desktop support.

**Comment by marandaneto** [comment]
@CaptainDario unfortunately not yet, but please upvote for gathering interest.

We'd need to write a pure Dart SDK (not depending on the Native SDKs such as Android and iOS for Desktop) or embed a Native SDK for Desktop, such as the Rust SDK.

However, adding macOS support should be easier since the iOS SDK supports a macOS target.

Which targets do you need? Win/Lin/macOS or all of them?

**Comment by CaptainDario** [comment]
Thank you for the quick response! I upvoted this issue.

I would need support for all platforms. But I also see quite an opportunity in supporting these platforms for this package. Because firebase does not support desktop, and everybody needing desktop support will look somewhere else (just like me)

**Comment by marandaneto** [comment]
A quick workaround, for now, is to just call the [API directly](https://posthog.com/tutorials/api-capture-events) until we provide first-class support for Flutter Desktop.

**Comment by CaptainDario** [comment]
I totally missed the direct API access, this seems like a good solution.

**Comment by CaptainDario** [comment]
@marandaneto How can I overwrite the default timestamp?
When I try to set it the events are not registered anymore in the web UI.

This works and the event is registered in the UI
``` dart
Map response = jsonDecode((await http.post(
    Uri.parse('https://eu.posthog.com/capture/'),
    headers: {
      "Content-Type": "application/json",
    },
    body: jsonEncode({
      "api_key": Env.POSTHOG_API_KEY,
      "event": eventName,
      "properties" : completeProps,
      //"timestamp" : DateTime(2023, 10, 5).toIso8601String(),
    })
  )).body);
```

this even is not registered.
``` dart
Map response = jsonDecode((await http.post(
    Uri.parse('https://eu.posthog.com/capture/'),
    headers: {
      "Content-Type": "application/json",
    },
    body: jsonEncode({
      "api_key": Env.POSTHOG_API_KEY,
      "event": eventName,
      "properties" : completeProps,
      "timestamp" : DateTime(2023, 10, 5).toIso8601String(),
    })
  )).body);
```

Do you have an idea how to overwrite it?

**Comment by CaptainDario** [comment]
For anybody finding this, the current time can be set with `(DateTime.now().toUtc()).toIso8601String()`.

**Comment by marandaneto** [comment]
> For anybody finding this, the current time can be set with `(DateTime.now().toUtc()).toIso8601String()`.

Yes, the [docs](https://posthog.com/tutorials/api-capture-events#adding-properties-and-batching) mention the ISO8601 format.

**Comment by CaptainDario** [comment]
Yes, they mention the format, but they did not mention (or I did not see) that the time needs to be normalized to UTC. When sending my time zone (UTC+1), the server did not return an error, it send the same response as with UTC but the data was not visible in the dashboard.

**Comment by marandaneto** [comment]
macOS support has landed at least https://github.com/PostHog/posthog-flutter/releases/tag/4.0.0-beta.2

**Comment by kirill-21** [comment]
Waiting for windows support

**Comment by mcquenji** [comment]
I've put together a quick 'n dirty posthog dart client https://github.com/necodeIT/posthog_dart for anyone interested

**Comment by Dieterbe** [comment]
is there a way to gracefully turn off posthog on unsupported platforms such as linux?

i have a codebase which i run for web (in production) and linux (for testing), so i'm happy with just the web support. but when i run on linux i get errors like:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method screen on channel posthog_flutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
<asynchronous suspension>
#1      PosthogFlutterIO.screen (package:posthog_flutter/src/posthog_flutter_io.dart:60:7)
<asynchronous suspension>
#2      _ProgrammerScreenState.initState (package:bodybuild/ui/programmer/page/programmer.dart:227:5)
<asynchronous suspension>

```

i have tried a patch like:
```
   await Posthog().setup(config);
 
+  if (!kIsWeb) {
+    await Posthog().disable();
+  }
+
```
but that just results in a black screen when i start the app on linux.

the only "solution" i see is wrapping every single call to Posthog()... with an kIsWeb check, obviously that's quite messy and i want to avoid that.

**Comment by marandaneto** [comment]
re https://posthog.com/questions/flutter-sdk-disable-for-unsupported-targets
@Dieterbe I think we have to have a NoOp at least so it does nothing on Linux and Window

**Comment by Dieterbe** [comment]
@marandaneto wow! this looks good. i was thinking that we'd manually set the no-op mode based on the platform, but doing it automatically works even better I think.

**Comment by fingoldo** [comment]
It's so weird. On your website you claim you ship fast. But you could not ship a Windows Desktop support in 3 years?

**Comment by marandaneto** [comment]
@stephane-archer https://github.com/PostHog/posthog-flutter/issues/170#issuecomment-2765438246
A Rust SDK already exists, but it's stateless (for backend use). We'd need to adapt and add a stateful mode as well, similar to our Node and RN SDKs, which share a core module.

**Comment by andronedev** [comment]
any updates ?

**Comment by marandaneto** [comment]
> any updates ?

sorry we've not prioritized this yet, we'll be having a new planning tomorrow and i'll get you an update if its something we're gonna do soon
